baseURL = 'https://derekroberts.github.io/hugo/'
languageCode = 'en-us'
title = 'Metacurious'
theme = 'PaperMod'

[params]
  description = "MetaCurious - Coaching for Leadership, Social Justice, and Relationships"
  author = "MetaCurious"
  showShareButtons = true
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = false
  showToc = true

[params.homeInfoParams]
  Title = "MetaCurious Coaching"
  Content = "Empowering emerging leaders to foster equitable communities through transformative coaching in leadership, social justice, and relationships."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "The Coach"
  url = "/about-the-coach/"
  weight = 30

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
